version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: demoDB
    ports:
      - "3307:3306"
    networks:
      - app-network

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app-container
    environment:
      SPRING_APPLICATION_JSON: >-
        {
          "spring.datasource.url": "jdbc:mysql://mariadb:3306/demoDB?useSSL=false",
          "spring.datasource.username": "root",
          "spring.datasource.password": "Admin@123"
        }
    ports:
      - "8081:8080"
    depends_on:
      - mariadb
    networks:
      - app-network


networks:
  app-network:
    driver: bridge