version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: demoDB
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mariadb_data:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  springboot-app:
    image: deeepsh/bhaktiquiz:v1
    environment:
      SPRING_APPLICATION_JSON: >-
        {
          "spring.datasource.url": "jdbc:mysql://mariadb:3306/demoDB?useSSL=false",
          "spring.datasource.username": "root",
          "spring.datasource.password": "Admin@123"
        }
    ports:
      - "8081:8080"
    networks:
      - app-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

volumes:
  mariadb_data:

networks:
  app-network:
    driver: overlay
