version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    # Assuming your Spring Boot app has a Dockerfile
    build: ../your-springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CORS_ALLOWED_ORIGINS=http://frontend:80,http://localhost:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
